source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'uglifier'
gem 'thin'
gem 'rails_config'
gem 'rails_12factor'