clients:
  kitchendaily:
    name: Kitchen Daily
    rollup: iD397SbcBlj
    newrelic_url: https://rpm.newrelic.com/accounts/159223/applications/1568411
    servers:
      web 1:
        name: Web 1
        code: Lt3esu5JvQ
      web 2:
        name: Web 2
        code: 8gruSwtairb
      web 3:
        name: Web 3
        code: 5peEtkXrePf
      web 4:
        name: Web 4
        code: jcOLXhOJKkM
  makers:
    name: Makers
    rollup: jhDrGe3aYwJ
    newrelic_url: https://rpm.newrelic.com/accounts/159223/applications/1568461
    servers:
      web a:
        name: Web A
        code: aiNXrs7o0xe
      web b:
        name: Web B
        code: 2jxLIQ0m3Dc
      web c:
        name: Web C
        code: 1HQuWlznmGc
      web d:
        name: Web D
        code: 1HQuWlznmGc
  homesessive:
    name: Homesessive
    rollup: 5FxPOW2STM0
    newrelic_url: https://rpm.newrelic.com/accounts/159223/applications/1630825
    servers:
      web 1:
        name: Web 1
        code: 48vgbIQLy1u
      web 2:
        name: Web 2
        code: hVWKB20QGDJ
      web 3:
        name: Web 3
        code: 7jbcy5Brnmw
      web 4:
        name: Web 4
        code: 75PCZ06gGnf
  aol-admin:
    name: AOL Admin
    rollup: j7Z3M32XZdK
    newrelic_url: https://rpm.newrelic.com/accounts/159223/applications/2496562
    servers:
      admin:
        name: Admin
        code: cxkklyGSxiN
  aol-staging:
    name: AOL Staging
    rollup: hqStgfhph4p
    newrelic_url: https://rpm.newrelic.com/accounts/159223/applications/1549538
    servers:
      staging:
        name: Staging
        code: 33JYBc6gnNt
  hightimes:
    name: High Times
    rollup: evlmPe5rJ6F
    newrelic_url: https://rpm.newrelic.com/accounts/159223/applications/1136225
    servers:
      web 1:
        name: Web 1
        code: 9HyjKls8x24
      web 2:
        name: Web 2
        code: 7wuHASEXywK
      web 3:
        name: Web 3
        code: jYrryF955bk
  bluegrass:
    name: The Bluegrass Situation
    rollup: 9DcTFIJ3EBV
    newrelic_url: https://rpm.newrelic.com/accounts/159223/applications/2138180
    servers:
      web 1:
        name: Web 1
        code: 4OdCxn9SPhl
      web 2:
        name: Web 2
        code: j3pglZ7TN0z
  illroots:
    name: ILLROOTS
    rollup: fQxnBKrRp1
    newrelic_url: https://rpm.newrelic.com/accounts/159223/applications/2536238
    servers:
      web 1:
        name: Web 1
        code: dlnEDuUnTcA
      admin:
        name: Admin
        code: aiSVE6UdfBs
  asics:
    name: ASICS
    rollup: jTXqoctDqEO
    newrelic_url: https://rpm.newrelic.com/accounts/159223/applications/1817668
    servers:
      web 1:
        name: Web 1
        code: 8dOikmwOHTv
      web 2:
        name: Web 2
        code: 7zaIMrBzUhK
