auth:
  enabled: true
  username: ashe
  password: avenue
loop:
  enabled: true
  seconds: 15
pods:
  kitchendaily:
    type: chart
    name: Kitchen Daily
    summary: 
      type: newrelic
      code: iD397SbcBlj
    links:
      newrelic:
        name: New Relic
        url: https://rpm.newrelic.com/accounts/159223/applications/1568411
    children:
      web 1:
        name: Web 1
        type: newrelic
        code: Lt3esu5JvQ
      web 2:
        name: Web 2 
        type: newrelic
        code: 8gruSwtairb
      web 3:
        name: Web 3
        type: newrelic
        code: 5peEtkXrePf
      web 4:
        name: Web 4
        type: newrelic
        code: jcOLXhOJKkM
  makers:
    type: chart
    name: Makers
    summary: 
      type: newrelic
      code: jhDrGe3aYwJ
    links:
      newrelic:
        name: New Relic
        url: https://rpm.newrelic.com/accounts/159223/applications/1568461
    children:
      web a:
        name: Web A
        type: newrelic
        code: aiNXrs7o0xe
      web b:
        name: Web B
        type: newrelic
        code: 2jxLIQ0m3Dc
      web c:
        name: Web C
        type: newrelic
        code: 1HQuWlznmGc
      web d:
        name: Web D
        type: newrelic
        code: 1HQuWlznmGc
  homesessive:
    type: chart
    name: Homesessive
    summary: 
      type: newrelic
      code: 5FxPOW2STM0
    links:
      newrelic:
        name: New Relic
        url: https://rpm.newrelic.com/accounts/159223/applications/1630825
    children:
      web 1:
        name: Web 1
        type: newrelic
        code: 48vgbIQLy1u
      web 2:
        name: Web 2
        type: newrelic
        code: hVWKB20QGDJ
      web 3:
        name: Web 3
        type: newrelic
        code: 7jbcy5Brnmw
      web 4:
        name: Web 4
        type: newrelic
        code: 75PCZ06gGnf
  aol-admin:
    type: chart
    name: AOL Admin
    summary: 
      type: newrelic
      code: j7Z3M32XZdK
    links:
      newrelic:
        name: New Relic
        url: https://rpm.newrelic.com/accounts/159223/applications/2496562
    children:
      admin:
        name: Admin
        type: newrelic
        code: cxkklyGSxiN
  aol-staging:
    type: chart
    name: AOL Staging
    summary: 
      type: newrelic
      code: hqStgfhph4p
    links:
      newrelic:
        name: New Relic
        url: https://rpm.newrelic.com/accounts/159223/applications/1549538
    children:
      staging:
        name: Staging
        type: newrelic
        code: 33JYBc6gnNt
  hightimes:
    type: chart
    name: High Times
    summary: 
      type: newrelic
      code: evlmPe5rJ6F
    links:
      newrelic:
        name: New Relic
        url: https://rpm.newrelic.com/accounts/159223/applications/1136225
    children:
      web 1:
        name: Web 1
        type: newrelic
        code: 9HyjKls8x24
      web 2:
        name: Web 2
        type: newrelic
        code: 7wuHASEXywK
      web 3:
        name: Web 3
        type: newrelic
        code: jYrryF955bk
  bluegrass:
    type: chart
    name: The Bluegrass Situation
    summary: 
      type: newrelic
      code: 9DcTFIJ3EBV
    links:
      newrelic:
        name: New Relic
        url: https://rpm.newrelic.com/accounts/159223/applications/2138180
    children:
      web 1:
        name: Web 1
        type: newrelic
        code: 4OdCxn9SPhl
      web 2:
        name: Web 2
        type: newrelic
        code: j3pglZ7TN0z
  illroots:
    type: chart
    name: ILLROOTS
    summary: 
      type: newrelic
      code: fQxnBKrRp1
    links:
      newrelic:
        name: New Relic
        url: https://rpm.newrelic.com/accounts/159223/applications/2536238
    children:
      web 1:
        name: Web 1
        type: newrelic
        code: dlnEDuUnTcA
      admin:
        name: Admin
        type: newrelic
        code: aiSVE6UdfBs
  asics:
    type: chart
    name: ASICS
    summary: 
      type: newrelic
      code: jTXqoctDqEO
    links:
      newrelic:
        name: New Relic
        url: https://rpm.newrelic.com/accounts/159223/applications/1817668
    children:
      web 1:
        name: Web 1
        type: newrelic
        code: 8dOikmwOHTv
      web 2:
        name: Web 2
        type: newrelic
        code: 7zaIMrBzUhK

