clients:
  kitchendaily:
    name: Kitchen Daily
    rollup: iD397SbcBlj
    newrelic_url: https://rpm.newrelic.com/accounts/159223/applications/1568411
    servers:
      web 1:
        name: Web 1
        code: Lt3esu5JvQ
      web 2:
        name: Web 2
        code: 8gruSwtairb
      web 3:
        name: Web 3
        code: 5peEtkXrePf
      web 4:
        name: Web 4
        code: jcOLXhOJKkM
  makers:
    name: Makers
    servers:
      web a:
        name: Web A
        code: aiNXrs7o0xe
      web b:
        name: Web B
        code: 2jxLIQ0m3Dc
      web c:
        name: Web C
        code: 1HQuWlznmGc
      web d:
        name: Web D
        code: 1HQuWlznmGc
  homesessive:
    name: Homesessive
    servers:
      web 1:
        name: Web 1
        code: 48vgbIQLy1u
      web 2:
        name: Web 2
        code: hVWKB20QGDJ
      web 3:
        name: Web 3
        code: 7jbcy5Brnmw
      web 4:
        name: Web 4
        code: 75PCZ06gGnf
  aol-other:
    name: AOL
    servers:
      admin:
        name: Admin
        code: cxkklyGSxiN
      staging:
        name: Staging
        code: 33JYBc6gnNt
  hightimes:
    name: High Times
    servers:
      web 1:
        name: Web 1
        code: 9HyjKls8x24
      web 2:
        name: Web 2
        code: 7wuHASEXywK
      web 3:
        name: Web 3
        code: jYrryF955bk
  bluegrass:
    name: The Bluegrass Situation
    servers:
      web 1:
        name: Web 1
        code: 4OdCxn9SPhl
      web 2:
        name: Web 2
        code: j3pglZ7TN0z
  illroots:
    name: ILLROOTS
    servers:
      web 1:
        name: Web 1
        code: dlnEDuUnTcA
      admin:
        name: Admin
        code: aiSVE6UdfBs
  asics:
    name: ASICS
    servers:
      web 1:
        name: Web 1
        code: 8dOikmwOHTv
      web 2:
        name: Web 2
        code: 7zaIMrBzUhK
